packages:
  - "apps/**"
  - "packages/**"
allowBuilds:
  '@parcel/watcher': false
  '@swc/core': false
  esbuild: false
  sharp: false
  unrs-resolver: false
packageExtensions:
  "@tailwindcss/node@*":
    dependencies:
      "@jridgewell/remapping": ^2.3.5
