/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'venue-variants': VenueVariant;
    'gastro-variants': GastroVariant;
    'entertainment-variants': EntertainmentVariant;
    activities: Activity;
    services: Service;
    'event-types': EventType;
    'venue-listings': VenueListing;
    'gastro-listings': GastroListing;
    'entertainment-listings': EntertainmentListing;
    spaces: Space;
    personnel: Personnel;
    companies: Company;
    cities: City;
    'place-types': PlaceType;
    rules: Rule;
    technologies: Technology;
    amenities: Amenity;
    'room-amenities': RoomAmenity;
    'food-types': FoodType;
    events: Event;
    'chat-messages': ChatMessage;
    inquiries: Inquiry;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'venue-variants': VenueVariantsSelect<false> | VenueVariantsSelect<true>;
    'gastro-variants': GastroVariantsSelect<false> | GastroVariantsSelect<true>;
    'entertainment-variants': EntertainmentVariantsSelect<false> | EntertainmentVariantsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    'venue-listings': VenueListingsSelect<false> | VenueListingsSelect<true>;
    'gastro-listings': GastroListingsSelect<false> | GastroListingsSelect<true>;
    'entertainment-listings': EntertainmentListingsSelect<false> | EntertainmentListingsSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    personnel: PersonnelSelect<false> | PersonnelSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'place-types': PlaceTypesSelect<false> | PlaceTypesSelect<true>;
    rules: RulesSelect<false> | RulesSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    'room-amenities': RoomAmenitiesSelect<false> | RoomAmenitiesSelect<true>;
    'food-types': FoodTypesSelect<false> | FoodTypesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      sendEmail: TaskSendEmail;
      sendPushNotification: TaskSendPushNotification;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: ('admin' | 'public-api')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-variants".
 */
export interface VenueVariant {
  id: string;
  listing?: (string | null) | VenueListing;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  type?: ('allYear' | 'seasonal') | null;
  availability: 'allDay' | 'selectedHours';
  selectedHours?: {
    from?: string | null;
    to?: string | null;
  };
  price: {
    generalPrice: number;
    seasonalPrices?:
      | {
          price: number;
          description?: string | null;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  includes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  includedSpaces?: (string | Space)[] | null;
  activities?: (string | Activity)[] | null;
  personnel?: (string | Personnel)[] | null;
  services?: (string | Service)[] | null;
  breakfast?: {
    included?: boolean | null;
    price?: number | null;
    loweredPrice?: number | null;
  };
  eventTypes?: (string | EventType)[] | null;
  images: {
    mainImage: string;
    gallery?:
      | {
          image?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-listings".
 */
export interface VenueListing {
  id: string;
  name: string;
  slug: string;
  company: string | Company;
  description?: string | null;
  shortDescription?: string | null;
  location: {
    address: string;
    city: string | City;
    postalCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  indoor?: boolean | null;
  outdoor?: boolean | null;
  eventTypes?: (string | EventType)[] | null;
  images: {
    coverImage: string;
    logo?: string | null;
    gallery?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  placeTypes?: (string | PlaceType)[] | null;
  capacity: number;
  area: number;
  canBeBookedAsWhole?: boolean | null;
  hasAccommodation?: boolean | null;
  accommodationCapacity?: number | null;
  venueRules?: (string | Rule)[] | null;
  foodAndDrinkRules?: (string | Rule)[] | null;
  personnel?: (string | Personnel)[] | null;
  amenities?: (string | Amenity)[] | null;
  technologies?: (string | Technology)[] | null;
  activities?: (string | Activity)[] | null;
  access?: {
    vehicleTypes?: ('car' | 'truck' | 'van' | 'bus')[] | null;
    helpWithLoadingAndUnloading?: boolean | null;
    loadingRamp?: boolean | null;
    loadingElevator?: boolean | null;
    serviceAccess?: boolean | null;
    serviceArea?: boolean | null;
  };
  storage?:
    | {
        name: string;
        area: number;
        space?: (string | null) | Space;
        accessedFrom?: (string | null) | Space;
        id?: string | null;
      }[]
    | null;
  activityAddons?:
    | {
        activity: string | Activity;
        price: number;
        space?: (string | null) | Space;
        type: 'indoor' | 'outdoor';
        id?: string | null;
      }[]
    | null;
  breakfast?: {
    included?: boolean | null;
    allowAccommodationWithoutBreakfast?: boolean | null;
    allowMoreBreakfastsThanAccommodation?: boolean | null;
    breakfastIsIncludedInPrice?: boolean | null;
    price?: number | null;
    pricePer?: ('person' | 'booking') | null;
    /**
     * Čas, od kterého je snídaně k dispozici (např. 07:00)
     */
    timeFrom?: string | null;
    /**
     * Čas, do kterého je snídaně k dispozici (např. 10:00)
     */
    timeTo?: string | null;
    foodTypes?: (string | FoodType)[] | null;
  };
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        groupedBy?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image?: string | null;
        eventName?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  ico: string;
  description?: string | null;
  email: string;
  phone?: string | null;
  website?: string | null;
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "place-types".
 */
export interface PlaceType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules".
 */
export interface Rule {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel".
 */
export interface Personnel {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: string;
  name: string;
  type: 'venue' | 'building' | 'room' | 'hall' | 'outdoor';
  parent?: (string | null) | Space;
  company: string | VenueListing;
  description?: string | null;
  /**
   * Maximální kapacita osob
   */
  capacity?: number | null;
  /**
   * Plocha v m²
   */
  area?: number | null;
  images?:
    | {
        image: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Indikuje, zda prostor nabízí ubytování
   */
  hasAccommodation?: boolean | null;
  /**
   * Kapacita ubytování (počet lůžek)
   */
  accommodationCapacity?: number | null;
  rooms?:
    | {
        name: string;
        capacity: number;
        countOfRoomsOfThisType: number;
        amenities?: (string | RoomAmenity)[] | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-amenities".
 */
export interface RoomAmenity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-types".
 */
export interface FoodType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-variants".
 */
export interface GastroVariant {
  id: string;
  listing?: (string | null) | GastroListing;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  type?: ('allYear' | 'seasonal') | null;
  availability: 'allDay' | 'selectedHours';
  selectedHours?: {
    from?: string | null;
    to?: string | null;
  };
  price: {
    generalPrice: number;
    seasonalPrices?:
      | {
          price: number;
          description?: string | null;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  includes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  includedSpaces?: (string | Space)[] | null;
  activities?: (string | Activity)[] | null;
  personnel?: (string | Personnel)[] | null;
  services?: (string | Service)[] | null;
  breakfast?: {
    included?: boolean | null;
    price?: number | null;
    loweredPrice?: number | null;
  };
  eventTypes?: (string | EventType)[] | null;
  images: {
    mainImage: string;
    gallery?:
      | {
          image?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-listings".
 */
export interface GastroListing {
  id: string;
  name: string;
  slug: string;
  company: string | Company;
  description?: string | null;
  shortDescription?: string | null;
  location: {
    address: string;
    city: string | City;
    postalCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  indoor?: boolean | null;
  outdoor?: boolean | null;
  eventTypes?: (string | EventType)[] | null;
  images: {
    coverImage: string;
    logo?: string | null;
    gallery?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  placeTypes?: (string | PlaceType)[] | null;
  capacity: number;
  area: number;
  canBeBookedAsWhole?: boolean | null;
  hasAccommodation?: boolean | null;
  accommodationCapacity?: number | null;
  venueRules?: (string | Rule)[] | null;
  foodAndDrinkRules?: (string | Rule)[] | null;
  personnel?: (string | Personnel)[] | null;
  amenities?: (string | Amenity)[] | null;
  technologies?: (string | Technology)[] | null;
  activities?: (string | Activity)[] | null;
  access?: {
    vehicleTypes?: ('car' | 'truck' | 'van' | 'bus')[] | null;
    helpWithLoadingAndUnloading?: boolean | null;
    loadingRamp?: boolean | null;
    loadingElevator?: boolean | null;
    serviceAccess?: boolean | null;
    serviceArea?: boolean | null;
  };
  storage?:
    | {
        name: string;
        area: number;
        space?: (string | null) | Space;
        accessedFrom?: (string | null) | Space;
        id?: string | null;
      }[]
    | null;
  activityAddons?:
    | {
        activity: string | Activity;
        price: number;
        space?: (string | null) | Space;
        type: 'indoor' | 'outdoor';
        id?: string | null;
      }[]
    | null;
  breakfast?: {
    included?: boolean | null;
    allowAccommodationWithoutBreakfast?: boolean | null;
    allowMoreBreakfastsThanAccommodation?: boolean | null;
    breakfastIsIncludedInPrice?: boolean | null;
    price?: number | null;
    pricePer?: ('person' | 'booking') | null;
    /**
     * Čas, od kterého je snídaně k dispozici (např. 07:00)
     */
    timeFrom?: string | null;
    /**
     * Čas, do kterého je snídaně k dispozici (např. 10:00)
     */
    timeTo?: string | null;
    foodTypes?: (string | FoodType)[] | null;
  };
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        groupedBy?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image?: string | null;
        eventName?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-variants".
 */
export interface EntertainmentVariant {
  id: string;
  listing?: (string | null) | EntertainmentListing;
  name: string;
  shortDescription?: string | null;
  description?: string | null;
  type?: ('allYear' | 'seasonal') | null;
  availability: 'allDay' | 'selectedHours';
  selectedHours?: {
    from?: string | null;
    to?: string | null;
  };
  price: {
    generalPrice: number;
    seasonalPrices?:
      | {
          price: number;
          description?: string | null;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  includes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  includedSpaces?: (string | Space)[] | null;
  activities?: (string | Activity)[] | null;
  personnel?: (string | Personnel)[] | null;
  services?: (string | Service)[] | null;
  breakfast?: {
    included?: boolean | null;
    price?: number | null;
    loweredPrice?: number | null;
  };
  eventTypes?: (string | EventType)[] | null;
  images: {
    mainImage: string;
    gallery?:
      | {
          image?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-listings".
 */
export interface EntertainmentListing {
  id: string;
  name: string;
  slug: string;
  company: string | Company;
  description?: string | null;
  shortDescription?: string | null;
  location: {
    address: string;
    city: string | City;
    postalCode?: string | null;
    latitude?: number | null;
    longitude?: number | null;
  };
  indoor?: boolean | null;
  outdoor?: boolean | null;
  eventTypes?: (string | EventType)[] | null;
  images: {
    coverImage: string;
    logo?: string | null;
    gallery?:
      | {
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  placeTypes?: (string | PlaceType)[] | null;
  capacity: number;
  area: number;
  canBeBookedAsWhole?: boolean | null;
  hasAccommodation?: boolean | null;
  accommodationCapacity?: number | null;
  venueRules?: (string | Rule)[] | null;
  foodAndDrinkRules?: (string | Rule)[] | null;
  personnel?: (string | Personnel)[] | null;
  amenities?: (string | Amenity)[] | null;
  technologies?: (string | Technology)[] | null;
  activities?: (string | Activity)[] | null;
  access?: {
    vehicleTypes?: ('car' | 'truck' | 'van' | 'bus')[] | null;
    helpWithLoadingAndUnloading?: boolean | null;
    loadingRamp?: boolean | null;
    loadingElevator?: boolean | null;
    serviceAccess?: boolean | null;
    serviceArea?: boolean | null;
  };
  storage?:
    | {
        name: string;
        area: number;
        space?: (string | null) | Space;
        accessedFrom?: (string | null) | Space;
        id?: string | null;
      }[]
    | null;
  activityAddons?:
    | {
        activity: string | Activity;
        price: number;
        space?: (string | null) | Space;
        type: 'indoor' | 'outdoor';
        id?: string | null;
      }[]
    | null;
  breakfast?: {
    included?: boolean | null;
    allowAccommodationWithoutBreakfast?: boolean | null;
    allowMoreBreakfastsThanAccommodation?: boolean | null;
    breakfastIsIncludedInPrice?: boolean | null;
    price?: number | null;
    pricePer?: ('person' | 'booking') | null;
    /**
     * Čas, od kterého je snídaně k dispozici (např. 07:00)
     */
    timeFrom?: string | null;
    /**
     * Čas, do kterého je snídaně k dispozici (např. 10:00)
     */
    timeTo?: string | null;
    foodTypes?: (string | FoodType)[] | null;
  };
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        groupedBy?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image?: string | null;
        eventName?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name: string;
  status: 'planning' | 'deactivated' | 'completed';
  eventType: string | EventType;
  budget?: number | null;
  notes?:
    | {
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  checklist?:
    | {
        item?: string | null;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  icon?: string | null;
  date: {
    start: string;
    end: string;
  };
  location?: {
    city?: (string | null) | City;
    address?: string | null;
    venue?: (string | null) | VenueListing;
  };
  guests: {
    adults: number;
    children: number;
    ztp?: boolean | null;
    pets?: boolean | null;
  };
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: string;
  inquiry: string | Inquiry;
  sender: string | User;
  senderType: 'user' | 'company';
  content: string;
  sentAt: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  companyStatus: 'pending' | 'confirmed' | 'declined';
  userStatus: 'pending' | 'confirmed' | 'cancelled';
  sentAt: string;
  lastCompanyMessageSentAt?: string | null;
  lastUserMessageSentAt?: string | null;
  lastUserSeenAt?: string | null;
  lastCompanySeenAt?: string | null;
  user: string | User;
  company: string | Company;
  event: string | Event;
  listingType: 'venue' | 'gastro' | 'entertainment';
  variant:
    | {
        relationTo: 'entertainment-variants';
        value: string | EntertainmentVariant;
      }
    | {
        relationTo: 'gastro-variants';
        value: string | GastroVariant;
      }
    | {
        relationTo: 'venue-variants';
        value: string | VenueVariant;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendEmail' | 'sendPushNotification';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendEmail' | 'sendPushNotification') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'venue-variants';
        value: string | VenueVariant;
      } | null)
    | ({
        relationTo: 'gastro-variants';
        value: string | GastroVariant;
      } | null)
    | ({
        relationTo: 'entertainment-variants';
        value: string | EntertainmentVariant;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'event-types';
        value: string | EventType;
      } | null)
    | ({
        relationTo: 'venue-listings';
        value: string | VenueListing;
      } | null)
    | ({
        relationTo: 'gastro-listings';
        value: string | GastroListing;
      } | null)
    | ({
        relationTo: 'entertainment-listings';
        value: string | EntertainmentListing;
      } | null)
    | ({
        relationTo: 'spaces';
        value: string | Space;
      } | null)
    | ({
        relationTo: 'personnel';
        value: string | Personnel;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'place-types';
        value: string | PlaceType;
      } | null)
    | ({
        relationTo: 'rules';
        value: string | Rule;
      } | null)
    | ({
        relationTo: 'technologies';
        value: string | Technology;
      } | null)
    | ({
        relationTo: 'amenities';
        value: string | Amenity;
      } | null)
    | ({
        relationTo: 'room-amenities';
        value: string | RoomAmenity;
      } | null)
    | ({
        relationTo: 'food-types';
        value: string | FoodType;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: string | ChatMessage;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-variants_select".
 */
export interface VenueVariantsSelect<T extends boolean = true> {
  listing?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  type?: T;
  availability?: T;
  selectedHours?:
    | T
    | {
        from?: T;
        to?: T;
      };
  price?:
    | T
    | {
        generalPrice?: T;
        seasonalPrices?:
          | T
          | {
              price?: T;
              description?: T;
              from?: T;
              to?: T;
              id?: T;
            };
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  includedSpaces?: T;
  activities?: T;
  personnel?: T;
  services?: T;
  breakfast?:
    | T
    | {
        included?: T;
        price?: T;
        loweredPrice?: T;
      };
  eventTypes?: T;
  images?:
    | T
    | {
        mainImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-variants_select".
 */
export interface GastroVariantsSelect<T extends boolean = true> {
  listing?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  type?: T;
  availability?: T;
  selectedHours?:
    | T
    | {
        from?: T;
        to?: T;
      };
  price?:
    | T
    | {
        generalPrice?: T;
        seasonalPrices?:
          | T
          | {
              price?: T;
              description?: T;
              from?: T;
              to?: T;
              id?: T;
            };
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  includedSpaces?: T;
  activities?: T;
  personnel?: T;
  services?: T;
  breakfast?:
    | T
    | {
        included?: T;
        price?: T;
        loweredPrice?: T;
      };
  eventTypes?: T;
  images?:
    | T
    | {
        mainImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-variants_select".
 */
export interface EntertainmentVariantsSelect<T extends boolean = true> {
  listing?: T;
  name?: T;
  shortDescription?: T;
  description?: T;
  type?: T;
  availability?: T;
  selectedHours?:
    | T
    | {
        from?: T;
        to?: T;
      };
  price?:
    | T
    | {
        generalPrice?: T;
        seasonalPrices?:
          | T
          | {
              price?: T;
              description?: T;
              from?: T;
              to?: T;
              id?: T;
            };
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  includedSpaces?: T;
  activities?: T;
  personnel?: T;
  services?: T;
  breakfast?:
    | T
    | {
        included?: T;
        price?: T;
        loweredPrice?: T;
      };
  eventTypes?: T;
  images?:
    | T
    | {
        mainImage?: T;
        gallery?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-listings_select".
 */
export interface VenueListingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  company?: T;
  description?: T;
  shortDescription?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  indoor?: T;
  outdoor?: T;
  eventTypes?: T;
  images?:
    | T
    | {
        coverImage?: T;
        logo?: T;
        gallery?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  placeTypes?: T;
  capacity?: T;
  area?: T;
  canBeBookedAsWhole?: T;
  hasAccommodation?: T;
  accommodationCapacity?: T;
  venueRules?: T;
  foodAndDrinkRules?: T;
  personnel?: T;
  amenities?: T;
  technologies?: T;
  activities?: T;
  access?:
    | T
    | {
        vehicleTypes?: T;
        helpWithLoadingAndUnloading?: T;
        loadingRamp?: T;
        loadingElevator?: T;
        serviceAccess?: T;
        serviceArea?: T;
      };
  storage?:
    | T
    | {
        name?: T;
        area?: T;
        space?: T;
        accessedFrom?: T;
        id?: T;
      };
  activityAddons?:
    | T
    | {
        activity?: T;
        price?: T;
        space?: T;
        type?: T;
        id?: T;
      };
  breakfast?:
    | T
    | {
        included?: T;
        allowAccommodationWithoutBreakfast?: T;
        allowMoreBreakfastsThanAccommodation?: T;
        breakfastIsIncludedInPrice?: T;
        price?: T;
        pricePer?: T;
        timeFrom?: T;
        timeTo?: T;
        foodTypes?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        groupedBy?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?: T;
        eventName?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-listings_select".
 */
export interface GastroListingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  company?: T;
  description?: T;
  shortDescription?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  indoor?: T;
  outdoor?: T;
  eventTypes?: T;
  images?:
    | T
    | {
        coverImage?: T;
        logo?: T;
        gallery?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  placeTypes?: T;
  capacity?: T;
  area?: T;
  canBeBookedAsWhole?: T;
  hasAccommodation?: T;
  accommodationCapacity?: T;
  venueRules?: T;
  foodAndDrinkRules?: T;
  personnel?: T;
  amenities?: T;
  technologies?: T;
  activities?: T;
  access?:
    | T
    | {
        vehicleTypes?: T;
        helpWithLoadingAndUnloading?: T;
        loadingRamp?: T;
        loadingElevator?: T;
        serviceAccess?: T;
        serviceArea?: T;
      };
  storage?:
    | T
    | {
        name?: T;
        area?: T;
        space?: T;
        accessedFrom?: T;
        id?: T;
      };
  activityAddons?:
    | T
    | {
        activity?: T;
        price?: T;
        space?: T;
        type?: T;
        id?: T;
      };
  breakfast?:
    | T
    | {
        included?: T;
        allowAccommodationWithoutBreakfast?: T;
        allowMoreBreakfastsThanAccommodation?: T;
        breakfastIsIncludedInPrice?: T;
        price?: T;
        pricePer?: T;
        timeFrom?: T;
        timeTo?: T;
        foodTypes?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        groupedBy?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?: T;
        eventName?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-listings_select".
 */
export interface EntertainmentListingsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  company?: T;
  description?: T;
  shortDescription?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        postalCode?: T;
        latitude?: T;
        longitude?: T;
      };
  indoor?: T;
  outdoor?: T;
  eventTypes?: T;
  images?:
    | T
    | {
        coverImage?: T;
        logo?: T;
        gallery?:
          | T
          | {
              url?: T;
              id?: T;
            };
      };
  placeTypes?: T;
  capacity?: T;
  area?: T;
  canBeBookedAsWhole?: T;
  hasAccommodation?: T;
  accommodationCapacity?: T;
  venueRules?: T;
  foodAndDrinkRules?: T;
  personnel?: T;
  amenities?: T;
  technologies?: T;
  activities?: T;
  access?:
    | T
    | {
        vehicleTypes?: T;
        helpWithLoadingAndUnloading?: T;
        loadingRamp?: T;
        loadingElevator?: T;
        serviceAccess?: T;
        serviceArea?: T;
      };
  storage?:
    | T
    | {
        name?: T;
        area?: T;
        space?: T;
        accessedFrom?: T;
        id?: T;
      };
  activityAddons?:
    | T
    | {
        activity?: T;
        price?: T;
        space?: T;
        type?: T;
        id?: T;
      };
  breakfast?:
    | T
    | {
        included?: T;
        allowAccommodationWithoutBreakfast?: T;
        allowMoreBreakfastsThanAccommodation?: T;
        breakfastIsIncludedInPrice?: T;
        price?: T;
        pricePer?: T;
        timeFrom?: T;
        timeTo?: T;
        foodTypes?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        groupedBy?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?: T;
        eventName?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  parent?: T;
  company?: T;
  description?: T;
  capacity?: T;
  area?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  hasAccommodation?: T;
  accommodationCapacity?: T;
  rooms?:
    | T
    | {
        name?: T;
        capacity?: T;
        countOfRoomsOfThisType?: T;
        amenities?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_select".
 */
export interface PersonnelSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  ico?: T;
  description?: T;
  email?: T;
  phone?: T;
  website?: T;
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "place-types_select".
 */
export interface PlaceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rules_select".
 */
export interface RulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-amenities_select".
 */
export interface RoomAmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-types_select".
 */
export interface FoodTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  eventType?: T;
  budget?: T;
  notes?:
    | T
    | {
        note?: T;
        id?: T;
      };
  checklist?:
    | T
    | {
        item?: T;
        completed?: T;
        id?: T;
      };
  icon?: T;
  date?:
    | T
    | {
        start?: T;
        end?: T;
      };
  location?:
    | T
    | {
        city?: T;
        address?: T;
        venue?: T;
      };
  guests?:
    | T
    | {
        adults?: T;
        children?: T;
        ztp?: T;
        pets?: T;
      };
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  inquiry?: T;
  sender?: T;
  senderType?: T;
  content?: T;
  sentAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  companyStatus?: T;
  userStatus?: T;
  sentAt?: T;
  lastCompanyMessageSentAt?: T;
  lastUserMessageSentAt?: T;
  lastUserSeenAt?: T;
  lastCompanySeenAt?: T;
  user?: T;
  company?: T;
  event?: T;
  listingType?: T;
  variant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    email: string;
    body: string;
    subject: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPushNotification".
 */
export interface TaskSendPushNotification {
  input: {
    title: string;
    message: string;
    accountId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

