/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    accounts: AccountAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'activity-groups': ActivityGroup;
    subscribes: Subscribe;
    'push-subscriptions': PushSubscription;
    'monthly-notifications': MonthlyNotification;
    accesses: Access;
    obligations: Obligation;
    accounts: Account;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'activity-groups': ActivityGroupsSelect<false> | ActivityGroupsSelect<true>;
    subscribes: SubscribesSelect<false> | SubscribesSelect<true>;
    'push-subscriptions': PushSubscriptionsSelect<false> | PushSubscriptionsSelect<true>;
    'monthly-notifications': MonthlyNotificationsSelect<false> | MonthlyNotificationsSelect<true>;
    accesses: AccessesSelect<false> | AccessesSelect<true>;
    obligations: ObligationsSelect<false> | ObligationsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Account & {
        collection: 'accounts';
      });
  jobs: {
    tasks: {
      sendEmail: TaskSendEmail;
      sendSms: TaskSendSms;
      createObligation: TaskCreateObligation;
      getRecord: TaskGetRecord;
      sendPushNotification: TaskSendPushNotification;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: {
      monthlyNotificationsWorkflow: WorkflowMonthlyNotificationsWorkflow;
      alertNotificationWorkflow: WorkflowAlertNotificationWorkflow;
      subscriptionActivatedWorkflow: WorkflowSubscriptionActivatedWorkflow;
      addMarketingContactWorkflow: WorkflowAddMarketingContactWorkflow;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AccountAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  role: ('admin' | 'public-api')[];
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-groups".
 */
export interface ActivityGroup {
  id: string;
  active?: boolean | null;
  /**
   * Unikátní identifikátor skupiny činností
   */
  slug: string;
  /**
   * Unikátní identifikátor od Stripe - Price ID
   */
  priceId: string;
  /**
   * Název pro katalog
   */
  label: string;
  /**
   * Název skupiny obchodních činností
   */
  name: string;
  /**
   * Název skupiny obchodních činností
   */
  mobileName?: string | null;
  /**
   * Popis skupiny činností
   */
  description: string;
  /**
   * Cena v korunách
   */
  price: number;
  /**
   * Seznam konkrétních činností v rámci této skupiny
   */
  items: {
    item: string;
    id?: string | null;
  }[];
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribes".
 */
export interface Subscribe {
  id: string;
  email: string;
  phone: string;
  phonePrefix: string;
  activityGroups: (string | ActivityGroup)[];
  notificationSettings?: {
    emailNotifications?: boolean | null;
    smsNotifications?: boolean | null;
    pushNotifications?: boolean | null;
  };
  terms: boolean;
  marketing?: boolean | null;
  active?: boolean | null;
  promocodeAlreadySent?: boolean | null;
  promotionCode?: string | null;
  stripeSubscribeId?: string | null;
  stripeCustomerId?: string | null;
  subscribeId: string;
  account: string | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: string;
  stripe?: {
    customerId?: string | null;
  };
  terms: boolean;
  marketing?: boolean | null;
  pushSubscription?: (string | PushSubscription)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions".
 */
export interface PushSubscription {
  id: string;
  endpoint: string;
  p256dh: string;
  auth: string;
  account?: (string | null) | Account;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-notifications".
 */
export interface MonthlyNotification {
  id: string;
  month:
    | 'Leden'
    | 'Únor'
    | 'Březen'
    | 'Duben'
    | 'Květen'
    | 'Červen'
    | 'Červenec'
    | 'Srpen'
    | 'Září'
    | 'Říjen'
    | 'Listopad'
    | 'Prosinec';
  year: string;
  useEmail?: boolean | null;
  useSms?: boolean | null;
  emailForTest?: string | null;
  phoneForTest?: string | null;
  notifications?:
    | {
        text: string;
        mobileText: string;
        description: string;
        link?: string | null;
        activityGroups: (string | ActivityGroup)[];
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accesses".
 */
export interface Access {
  id: string;
  activityGroups?: (string | ActivityGroup)[] | null;
  monthlyNotification: string | MonthlyNotification;
  subscribe: string | Subscribe;
  subscribeId: string;
  accessId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "obligations".
 */
export interface Obligation {
  id: string;
  text: string;
  mobileText: string;
  description: string;
  link?: string | null;
  activityGroups: (string | ActivityGroup)[];
  date: string;
  monthlyNotificationId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendEmail' | 'sendSms' | 'createObligation' | 'getRecord' | 'sendPushNotification';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  workflowSlug?:
    | (
        | 'monthlyNotificationsWorkflow'
        | 'alertNotificationWorkflow'
        | 'subscriptionActivatedWorkflow'
        | 'addMarketingContactWorkflow'
      )
    | null;
  taskSlug?: ('inline' | 'sendEmail' | 'sendSms' | 'createObligation' | 'getRecord' | 'sendPushNotification') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'activity-groups';
        value: string | ActivityGroup;
      } | null)
    | ({
        relationTo: 'subscribes';
        value: string | Subscribe;
      } | null)
    | ({
        relationTo: 'push-subscriptions';
        value: string | PushSubscription;
      } | null)
    | ({
        relationTo: 'monthly-notifications';
        value: string | MonthlyNotification;
      } | null)
    | ({
        relationTo: 'accesses';
        value: string | Access;
      } | null)
    | ({
        relationTo: 'obligations';
        value: string | Obligation;
      } | null)
    | ({
        relationTo: 'accounts';
        value: string | Account;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'accounts';
        value: string | Account;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'accounts';
        value: string | Account;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activity-groups_select".
 */
export interface ActivityGroupsSelect<T extends boolean = true> {
  active?: T;
  slug?: T;
  priceId?: T;
  label?: T;
  name?: T;
  mobileName?: T;
  description?: T;
  price?: T;
  items?:
    | T
    | {
        item?: T;
        id?: T;
      };
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribes_select".
 */
export interface SubscribesSelect<T extends boolean = true> {
  email?: T;
  phone?: T;
  phonePrefix?: T;
  activityGroups?: T;
  notificationSettings?:
    | T
    | {
        emailNotifications?: T;
        smsNotifications?: T;
        pushNotifications?: T;
      };
  terms?: T;
  marketing?: T;
  active?: T;
  promocodeAlreadySent?: T;
  promotionCode?: T;
  stripeSubscribeId?: T;
  stripeCustomerId?: T;
  subscribeId?: T;
  account?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "push-subscriptions_select".
 */
export interface PushSubscriptionsSelect<T extends boolean = true> {
  endpoint?: T;
  p256dh?: T;
  auth?: T;
  account?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "monthly-notifications_select".
 */
export interface MonthlyNotificationsSelect<T extends boolean = true> {
  month?: T;
  year?: T;
  useEmail?: T;
  useSms?: T;
  emailForTest?: T;
  phoneForTest?: T;
  notifications?:
    | T
    | {
        text?: T;
        mobileText?: T;
        description?: T;
        link?: T;
        activityGroups?: T;
        date?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accesses_select".
 */
export interface AccessesSelect<T extends boolean = true> {
  activityGroups?: T;
  monthlyNotification?: T;
  subscribe?: T;
  subscribeId?: T;
  accessId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "obligations_select".
 */
export interface ObligationsSelect<T extends boolean = true> {
  text?: T;
  mobileText?: T;
  description?: T;
  link?: T;
  activityGroups?: T;
  date?: T;
  monthlyNotificationId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  stripe?:
    | T
    | {
        customerId?: T;
      };
  terms?: T;
  marketing?: T;
  pushSubscription?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  workflowSlug?: T;
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    email: string;
    body: string;
    subject: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendSms".
 */
export interface TaskSendSms {
  input: {
    phone: string;
    phonePrefix: string;
    smsBody: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateObligation".
 */
export interface TaskCreateObligation {
  input: {
    text: string;
    mobileText?: string | null;
    link?: string | null;
    description?: string | null;
    date?: string | null;
    activityGroups: {
      activityGroupId: string;
    }[];
    monthlyNotificationId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGetRecord".
 */
export interface TaskGetRecord {
  input: {
    id: string;
    collection: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPushNotification".
 */
export interface TaskSendPushNotification {
  input: {
    title: string;
    message: string;
    accountId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowMonthlyNotificationsWorkflow".
 */
export interface WorkflowMonthlyNotificationsWorkflow {
  input: {
    monthlyNotificationId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowAlertNotificationWorkflow".
 */
export interface WorkflowAlertNotificationWorkflow {
  input: {
    obligationId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowSubscriptionActivatedWorkflow".
 */
export interface WorkflowSubscriptionActivatedWorkflow {
  input: {
    promotionCode?: string | null;
    email: string;
    accountEmail: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "WorkflowAddMarketingContactWorkflow".
 */
export interface WorkflowAddMarketingContactWorkflow {
  input: {
    subscriptionId: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}