/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    districts: District;
    necessities: Necessity;
    'entertainment-types': EntertainmentType;
    'dietary-options': DietaryOption;
    'food-service-types': FoodServiceType;
    regions: Region;
    'dish-types': DishType;
    users: User;
    admins: Admin;
    'user-media': UserMedia;
    variants: Variant;
    activities: Activity;
    services: Service;
    'event-types': EventType;
    listings: Listing;
    spaces: Space;
    personnel: Personnel;
    companies: Company;
    countries: Country;
    cities: City;
    'place-types': PlaceType;
    'venue-rules': VenueRule;
    'gastro-rules': GastroRule;
    'entertainment-rules': EntertainmentRule;
    'food-preparation-styles': FoodPreparationStyle;
    'space-rules': SpaceRule;
    'music-genres': MusicGenre;
    technologies: Technology;
    amenities: Amenity;
    'room-amenities': RoomAmenity;
    cuisines: Cuisine;
    events: Event;
    'chat-messages': ChatMessage;
    inquiries: Inquiry;
    'calendar-events': CalendarEvent;
    'favourite-listings': FavouriteListing;
    invitations: Invitation;
    'space-types': SpaceType;
    'listing-entertainment-details': ListingEntertainmentDetail;
    'listing-gastro-details': ListingGastroDetail;
    'listing-venue-details': ListingVenueDetail;
    'roadmap-items': RoadmapItem;
    'user-notifications': UserNotification;
    'listing-subscriptions': ListingSubscription;
    'oauth-accounts': OauthAccount;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    districts: DistrictsSelect<false> | DistrictsSelect<true>;
    necessities: NecessitiesSelect<false> | NecessitiesSelect<true>;
    'entertainment-types': EntertainmentTypesSelect<false> | EntertainmentTypesSelect<true>;
    'dietary-options': DietaryOptionsSelect<false> | DietaryOptionsSelect<true>;
    'food-service-types': FoodServiceTypesSelect<false> | FoodServiceTypesSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    'dish-types': DishTypesSelect<false> | DishTypesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'user-media': UserMediaSelect<false> | UserMediaSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'event-types': EventTypesSelect<false> | EventTypesSelect<true>;
    listings: ListingsSelect<false> | ListingsSelect<true>;
    spaces: SpacesSelect<false> | SpacesSelect<true>;
    personnel: PersonnelSelect<false> | PersonnelSelect<true>;
    companies: CompaniesSelect<false> | CompaniesSelect<true>;
    countries: CountriesSelect<false> | CountriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'place-types': PlaceTypesSelect<false> | PlaceTypesSelect<true>;
    'venue-rules': VenueRulesSelect<false> | VenueRulesSelect<true>;
    'gastro-rules': GastroRulesSelect<false> | GastroRulesSelect<true>;
    'entertainment-rules': EntertainmentRulesSelect<false> | EntertainmentRulesSelect<true>;
    'food-preparation-styles': FoodPreparationStylesSelect<false> | FoodPreparationStylesSelect<true>;
    'space-rules': SpaceRulesSelect<false> | SpaceRulesSelect<true>;
    'music-genres': MusicGenresSelect<false> | MusicGenresSelect<true>;
    technologies: TechnologiesSelect<false> | TechnologiesSelect<true>;
    amenities: AmenitiesSelect<false> | AmenitiesSelect<true>;
    'room-amenities': RoomAmenitiesSelect<false> | RoomAmenitiesSelect<true>;
    cuisines: CuisinesSelect<false> | CuisinesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    'calendar-events': CalendarEventsSelect<false> | CalendarEventsSelect<true>;
    'favourite-listings': FavouriteListingsSelect<false> | FavouriteListingsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    'space-types': SpaceTypesSelect<false> | SpaceTypesSelect<true>;
    'listing-entertainment-details': ListingEntertainmentDetailsSelect<false> | ListingEntertainmentDetailsSelect<true>;
    'listing-gastro-details': ListingGastroDetailsSelect<false> | ListingGastroDetailsSelect<true>;
    'listing-venue-details': ListingVenueDetailsSelect<false> | ListingVenueDetailsSelect<true>;
    'roadmap-items': RoadmapItemsSelect<false> | RoadmapItemsSelect<true>;
    'user-notifications': UserNotificationsSelect<false> | UserNotificationsSelect<true>;
    'listing-subscriptions': ListingSubscriptionsSelect<false> | ListingSubscriptionsSelect<true>;
    'oauth-accounts': OauthAccountsSelect<false> | OauthAccountsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user:
    | (User & {
        collection: 'users';
      })
    | (Admin & {
        collection: 'admins';
      });
  jobs: {
    tasks: {
      sendEmail: TaskSendEmail;
      sendPushNotification: TaskSendPushNotification;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts".
 */
export interface District {
  id: string;
  name: string;
  slug: string;
  code: string;
  region: string;
  country: 'cz';
  bboxMinLon: number;
  bboxMinLat: number;
  bboxMaxLon: number;
  bboxMaxLat: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "necessities".
 */
export interface Necessity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-types".
 */
export interface EntertainmentType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary-options".
 */
export interface DietaryOption {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-service-types".
 */
export interface FoodServiceType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: string;
  name: string;
  slug: string;
  code: string;
  country: 'cz';
  bboxMinLon: number;
  bboxMinLat: number;
  bboxMaxLon: number;
  bboxMaxLat: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dish-types".
 */
export interface DishType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  firstName: string;
  lastName: string;
  phone?: {
    countryCode?: '420' | null;
    number?: string | null;
  };
  roles: ('user' | 'company')[];
  gdprConsent: boolean;
  termsOfUseConsent: boolean;
  lastRoadmapVoteAt?: string | null;
  marketingConsent?: boolean | null;
  loginToken?: string | null;
  loginTokenExpiration?: string | null;
  emailVerificationToken?: string | null;
  emailVerificationTokenExpiration?: string | null;
  pendingEmail?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: string;
  role: ('admin' | 'public-api')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-media".
 */
export interface UserMedia {
  id: string;
  filename: string;
  alt?: string | null;
  width?: number | null;
  height?: number | null;
  size?: number | null;
  mimeType?: string | null;
  bucket?: ('listings-images' | 'listings-videos') | null;
  user: string | User;
  status: 'active' | 'disabled' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  listing: string | Listing;
  status: 'active' | 'inactive' | 'disabled' | 'archived';
  capacity: {
    min?: number | null;
    max?: number | null;
  };
  name: string;
  shortDescription: string;
  description?: string | null;
  price: {
    base: number;
    pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
    seasonalPrices?:
      | {
          amount: number;
          adjustmentType: 'surcharge' | 'discount';
          valueType: 'absolute' | 'percentage';
          title: string;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  includes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  excludes?:
    | {
        item?: string | null;
        id?: string | null;
      }[]
    | null;
  duration?: {
    hasExactDuration?: boolean | null;
    exactDurationMinutes?: number | null;
    maxDurationMinutes?: number | null;
  };
  images: {
    coverImage: {
      filename?: string | null;
      alt?: string | null;
      width?: number | null;
      height?: number | null;
      size?: number | null;
      mimeType?: string | null;
      bucket?: ('listings-images' | 'listings-videos') | null;
    };
    gallery?:
      | {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
          id?: string | null;
        }[]
      | null;
  };
  details: (
    | {
        includedSpaces?: (string | Space)[] | null;
        accommodation: {
          included?: boolean | null;
          capacity?: number | null;
        };
        breakfast: {
          included?: boolean | null;
          price?: number | null;
          loweredPrice?: number | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'venue';
      }
    | {
        kidsMenu?: boolean | null;
        alcoholIncluded?: boolean | null;
        minimumOrderAmount?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'gastro';
      }
    | {
        audience?: ('adults' | 'kids' | 'seniors')[] | null;
        performance: {
          entertainmentIsPerformance?: boolean | null;
          numberOfSets?: number | null;
          pauseBetweenSetsInMinutes?: number | null;
        };
        id?: string | null;
        blockName?: string | null;
        blockType: 'entertainment';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings".
 */
export interface Listing {
  id: string;
  tariff: 'basic';
  type: 'venue' | 'gastro' | 'entertainment';
  subType?: string | null;
  filters: {
    eventTypes?: (string | EventType)[] | null;
    allEventTypes?: boolean | null;
    necessities?: (string | Necessity)[] | null;
    placeTypes?: (string | PlaceType)[] | null;
    venueRules?: (string | VenueRule)[] | null;
    musicGenres?: (string | MusicGenre)[] | null;
    entertainmentRules?: (string | EntertainmentRule)[] | null;
    gastroRules?: (string | GastroRule)[] | null;
    dietaryOptions?: (string | DietaryOption)[] | null;
    dishTypes?: (string | DishType)[] | null;
  };
  options: {
    cuisines?: (string | Cuisine)[] | null;
    foodPreparationStyles?: (string | FoodPreparationStyle)[] | null;
    services?: (string | Service)[] | null;
    technologies?: (string | Technology)[] | null;
    personnel?: (string | Personnel)[] | null;
    amenities?: (string | Amenity)[] | null;
    activities?: (string | Activity)[] | null;
  };
  detail:
    | {
        relationTo: 'listing-venue-details';
        value: string | ListingVenueDetail;
      }
    | {
        relationTo: 'listing-gastro-details';
        value: string | ListingGastroDetail;
      }
    | {
        relationTo: 'listing-entertainment-details';
        value: string | ListingEntertainmentDetail;
      };
  location: {
    /**
     * @minItems 2
     * @maxItems 2
     */
    point: [number, number];
    address: string;
    city: string | City;
    country: 'cz';
  };
  servicableArea: {
    wholeCountry: boolean;
    maxTravelDistanceKm?: number | null;
  };
  name: string;
  slug: string;
  status: 'active' | 'inactive' | 'disabled' | 'archived';
  subscriptionStatus: 'unpaid' | 'paid' | 'cancelling' | 'expired';
  company: string | Company;
  description?: string | null;
  shortDescription: string;
  indoor?: boolean | null;
  outdoor?: boolean | null;
  guests: {
    min?: number | null;
    max?: number | null;
    ztp?: boolean | null;
    pets?: boolean | null;
  };
  images: {
    coverImage: {
      filename: string;
      alt?: string | null;
      width?: number | null;
      height?: number | null;
      size?: number | null;
      mimeType?: string | null;
      bucket?: ('listings-images' | 'listings-videos') | null;
    };
    logo?: {
      filename?: string | null;
      alt?: string | null;
      width?: number | null;
      height?: number | null;
      size?: number | null;
      mimeType?: string | null;
      bucket?: ('listings-images' | 'listings-videos') | null;
    };
    gallery: {
      filename: string;
      alt?: string | null;
      width?: number | null;
      height?: number | null;
      size?: number | null;
      mimeType?: string | null;
      bucket?: ('listings-images' | 'listings-videos') | null;
      id?: string | null;
    }[];
  };
  minimumPricePerEvent: number;
  pricingUnit?: ('per_day' | 'per_person' | 'per_hour' | 'lump_sum') | null;
  minimumVariantPrice?: number | null;
  variantPricingUnit?: ('per_day' | 'per_person' | 'per_hour' | 'lump_sum') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types".
 */
export interface EventType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "place-types".
 */
export interface PlaceType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-rules".
 */
export interface VenueRule {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-genres".
 */
export interface MusicGenre {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-rules".
 */
export interface EntertainmentRule {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-rules".
 */
export interface GastroRule {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines".
 */
export interface Cuisine {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-preparation-styles".
 */
export interface FoodPreparationStyle {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies".
 */
export interface Technology {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel".
 */
export interface Personnel {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities".
 */
export interface Amenity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-venue-details".
 */
export interface ListingVenueDetail {
  id: string;
  customSections?:
    | (
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery1';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery2';
          }
        | {
            title: string;
            text?: string | null;
            images?:
              | {
                  filename: string;
                  alt?: string | null;
                  width?: number | null;
                  height?: number | null;
                  size?: number | null;
                  mimeType?: string | null;
                  bucket?: ('listings-images' | 'listings-videos') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery4';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery5';
          }
      )[]
    | null;
  sectionOrder?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        group?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        eventName: string;
        description?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        id?: string | null;
      }[]
    | null;
  type: 'venue';
  spacesType: 'area' | 'building' | 'room';
  area: number;
  canBeBookedAsWhole?: boolean | null;
  accomodation: {
    hasAccommodation?: boolean | null;
    accommodationCapacity?: number | null;
  };
  propertyAccess: {
    vehicleTypes?: ('car' | 'truck' | 'van' | 'bus')[] | null;
    loadingRamp?: boolean | null;
    loadingElevator?: boolean | null;
    serviceAccess?: boolean | null;
    serviceArea?: boolean | null;
  };
  storage?:
    | {
        name: string;
        area: number;
        space?: (string | null) | Space;
        accessedFrom?: (string | null) | Space;
        id?: string | null;
      }[]
    | null;
  parking: {
    hasParking?: boolean | null;
    parkingCapacity?: number | null;
    parkingIsIncludedInPrice?: boolean | null;
    parkingPrice?: number | null;
    parkingPriceUnit?: ('space' | 'event') | null;
  };
  filters: {
    allEventTypes: boolean;
    eventTypes?: (string | EventType)[] | null;
    placeTypes?: (string | PlaceType)[] | null;
    venueRules?: (string | VenueRule)[] | null;
    necessities?: (string | Necessity)[] | null;
  };
  options: {
    activities?:
      | {
          activity: string | Activity;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    technologies?:
      | {
          technology: string | Technology;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    personnel?:
      | {
          personnel: string | Personnel;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    amenities?:
      | {
          amenity: string | Amenity;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    services?:
      | {
          service: string | Service;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  catering: {
    hasCatering?: boolean | null;
    cateringIsIncludedInPrice?: boolean | null;
    price?: number | null;
    pricingUnit?: ('per_person' | 'per_hour' | 'lump_sum') | null;
    cuisines?:
      | {
          cuisine: string | Cuisine;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    foodPreparationStyles?:
      | {
          foodPreparationStyle: string | FoodPreparationStyle;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  breakfast: {
    breakfastIncluded: boolean;
    allowAccommodationWithoutBreakfast?: boolean | null;
    allowMoreBreakfastsThanAccommodation?: boolean | null;
    breakfastIsIncludedInPrice?: boolean | null;
    price?: number | null;
    priceUnit?: ('person' | 'booking') | null;
    /**
     * Čas, od kterého je snídaně k dispozici (např. 07:00)
     */
    timeFrom?: string | null;
    /**
     * Čas, do kterého je snídaně k dispozici (např. 10:00)
     */
    timeTo?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces".
 */
export interface Space {
  id: string;
  status: 'active' | 'disabled' | 'archived';
  price: {
    base: number;
    pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
    seasonalPrices?:
      | {
          amount: number;
          adjustmentType: 'surcharge' | 'discount';
          valueType: 'absolute' | 'percentage';
          title: string;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
  };
  name: string;
  type: 'area' | 'building' | 'room';
  parent?: (string | null) | Space;
  listing: string | Listing;
  description?: string | null;
  /**
   * Maximální kapacita osob
   */
  capacity?: number | null;
  /**
   * Plocha v m²
   */
  area?: number | null;
  images?:
    | {
        filename?: string | null;
        alt?: string | null;
        width?: number | null;
        height?: number | null;
        size?: number | null;
        mimeType?: string | null;
        bucket?: ('listings-images' | 'listings-videos') | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Indikuje, zda prostor nabízí ubytování
   */
  hasAccommodation?: boolean | null;
  /**
   * Kapacita ubytování (počet lůžek)
   */
  accommodationCapacity?: number | null;
  accommodationRooms?:
    | {
        name: string;
        capacity: number;
        countOfRoomsOfThisType: number;
        amenities?: (string | RoomAmenity)[] | null;
        id?: string | null;
      }[]
    | null;
  spaceRules?: (string | SpaceRule)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-amenities".
 */
export interface RoomAmenity {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-rules".
 */
export interface SpaceRule {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-gastro-details".
 */
export interface ListingGastroDetail {
  id: string;
  customSections?:
    | (
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery1';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery2';
          }
        | {
            title: string;
            text?: string | null;
            images?:
              | {
                  filename: string;
                  alt?: string | null;
                  width?: number | null;
                  height?: number | null;
                  size?: number | null;
                  mimeType?: string | null;
                  bucket?: ('listings-images' | 'listings-videos') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery4';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery5';
          }
      )[]
    | null;
  sectionOrder?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  price: {
    base: number;
    pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
    seasonalPrices?:
      | {
          amount: number;
          adjustmentType: 'surcharge' | 'discount';
          valueType: 'absolute' | 'percentage';
          title: string;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
    travelFeeEnabled?: boolean | null;
    travelFeePerKm?: number | null;
    travelFeeType?: ('one_way' | 'round_trip') | null;
    travelFeeStartsAtKm?: number | null;
  };
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        group?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        eventName: string;
        description?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        id?: string | null;
      }[]
    | null;
  type: 'gastro';
  alcohol: {
    servesAlcohol: boolean;
    pricingUnit: 'per_person' | 'per_event';
  };
  kidsMenu?: boolean | null;
  filters: {
    allEventTypes: boolean;
    eventTypes?: (string | EventType)[] | null;
    dishTypes?: (string | DishType)[] | null;
    necessities?: (string | Necessity)[] | null;
    dietaryOptions?: (string | DietaryOption)[] | null;
    gastroRules?: (string | GastroRule)[] | null;
  };
  options: {
    cuisines?:
      | {
          cuisine: string | Cuisine;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    foodPreparationStyles?:
      | {
          foodPreparationStyle: string | FoodPreparationStyle;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    services?:
      | {
          service: string | Service;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    personnel?:
      | {
          personnel: string | Personnel;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  setupAndTearDown: {
    setupTime?: number | null;
    tearDownTime?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-entertainment-details".
 */
export interface ListingEntertainmentDetail {
  id: string;
  customSections?:
    | (
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery1';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery2';
          }
        | {
            title: string;
            text?: string | null;
            images?:
              | {
                  filename: string;
                  alt?: string | null;
                  width?: number | null;
                  height?: number | null;
                  size?: number | null;
                  mimeType?: string | null;
                  bucket?: ('listings-images' | 'listings-videos') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery4';
          }
        | {
            title: string;
            text?: string | null;
            images: {
              filename: string;
              alt?: string | null;
              width?: number | null;
              height?: number | null;
              size?: number | null;
              mimeType?: string | null;
              bucket?: ('listings-images' | 'listings-videos') | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery5';
          }
      )[]
    | null;
  sectionOrder?:
    | {
        key: string;
        id?: string | null;
      }[]
    | null;
  price: {
    base: number;
    pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
    seasonalPrices?:
      | {
          amount: number;
          adjustmentType: 'surcharge' | 'discount';
          valueType: 'absolute' | 'percentage';
          title: string;
          from: string;
          to: string;
          id?: string | null;
        }[]
      | null;
    travelFeeEnabled?: boolean | null;
    travelFeePerKm?: number | null;
    travelFeeType?: ('one_way' | 'round_trip') | null;
    travelFeeStartsAtKm?: number | null;
  };
  faq?:
    | {
        active?: boolean | null;
        question: string;
        answer: string;
        group?: ('general' | 'booking' | 'cancellation' | 'payment' | 'other') | null;
        id?: string | null;
      }[]
    | null;
  references?:
    | {
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        eventName: string;
        description?: string | null;
        clientName?: string | null;
        eventType?: (string | null) | EventType;
        id?: string | null;
      }[]
    | null;
  employees?:
    | {
        name: string;
        role: string;
        description?: string | null;
        image: {
          filename?: string | null;
          alt?: string | null;
          width?: number | null;
          height?: number | null;
          size?: number | null;
          mimeType?: string | null;
          bucket?: ('listings-images' | 'listings-videos') | null;
        };
        id?: string | null;
      }[]
    | null;
  type: 'entertainment';
  audience?: ('adults' | 'kids' | 'seniors')[] | null;
  filters: {
    allEventTypes: boolean;
    eventTypes?: (string | EventType)[] | null;
    necessities?: (string | Necessity)[] | null;
    musicGenres?: (string | MusicGenre)[] | null;
    entertainmentRules?: (string | EntertainmentRule)[] | null;
  };
  options: {
    technologies?:
      | {
          technology: string | Technology;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    services?:
      | {
          service: string | Service;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
  };
  setupAndTearDown: {
    setupTime?: number | null;
    tearDownTime?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: string;
  name: string;
  slug: string;
  code: string;
  district: string;
  region: string;
  country: 'cz';
  latitude: number;
  longitude: number;
  bboxMinLon: number;
  bboxMinLat: number;
  bboxMaxLon: number;
  bboxMaxLat: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies".
 */
export interface Company {
  id: string;
  name: string;
  slug: string;
  status: 'active' | 'disabled' | 'archived';
  ico: string;
  description?: string | null;
  logo: {
    filename?: string | null;
    alt?: string | null;
    width?: number | null;
    height?: number | null;
    size?: number | null;
    mimeType?: string | null;
    bucket?: ('listings-images' | 'listings-videos') | null;
  };
  email: string;
  phone: {
    countryCode: '420';
    number: string;
  };
  website?: string | null;
  owner: string | User;
  billingAddress: {
    street: string;
    city: string;
    postalCode: string;
    country: string;
  };
  vatId?: string | null;
  members?:
    | {
        user: string | User;
        invitationEmail: string;
        role: 'admin' | 'manager' | 'editor';
        id?: string | null;
      }[]
    | null;
  /**
   * Stripe Customer ID (cus_...)
   */
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries".
 */
export interface Country {
  id: string;
  name: string;
  slug: string;
  code: string;
  latitude: number;
  longitude: number;
  bboxMinLon: number;
  bboxMinLat: number;
  bboxMaxLon: number;
  bboxMaxLat: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  name: string;
  status: 'active' | 'disabled' | 'archived' | 'completed';
  eventType: string | EventType;
  budget?: number | null;
  notes?:
    | {
        title: string;
        createdAt: string;
        description?: string | null;
        status: 'active' | 'archived';
        id?: string | null;
      }[]
    | null;
  checklist?:
    | {
        label: string;
        description?: string | null;
        dueDate?: string | null;
        completed?: boolean | null;
        priority?: ('low' | 'medium' | 'high') | null;
        status: 'active' | 'archived';
        id?: string | null;
      }[]
    | null;
  icon?: string | null;
  date: {
    start: string;
    end: string;
  };
  sharing: {
    confirmedInquiries?: boolean | null;
    place?: boolean | null;
  };
  location: {
    district: string | District;
    city?: (string | null) | City;
    address?: string | null;
    spaceType?: (string | null) | SpaceType;
    description?: string | null;
  };
  guests: {
    adults: number;
    children: number;
    ztp?: boolean | null;
    pets?: boolean | null;
  };
  contactPerson: {
    name: string;
    email: string;
    phone?: {
      countryCode?: '420' | null;
      number?: string | null;
    };
  };
  owner: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-types".
 */
export interface SpaceType {
  id: string;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: string;
  inquiry: string | Inquiry;
  sender: string | User;
  senderType: 'user' | 'company';
  content?:
    | (
        | {
            text?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            text?: string | null;
            answer?: string | null;
            answeredAt?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'question';
          }
      )[]
    | null;
  sentAt: string;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: string;
  user: string | User;
  listing: string | Listing;
  variant?: (string | null) | Variant;
  event: string | Event;
  listingType: 'venue' | 'gastro' | 'entertainment';
  customRequest: {
    note?: string | null;
    addons?:
      | {
          name: string;
          optionId: string;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          unitPrice: number;
          quantity: number;
          id?: string | null;
        }[]
      | null;
    spaces?:
      | {
          spaceId: string;
          name: string;
          price?: number | null;
          pricingUnit: 'per_day' | 'per_person' | 'per_hour' | 'lump_sum';
          id?: string | null;
        }[]
      | null;
    customRequirements?:
      | {
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    accommodation?: {
      guests?: number | null;
    };
    breakfast?: {
      guests?: number | null;
    };
    parking?: {
      spots?: number | null;
    };
  };
  serviceTime?: {
    startTime?: string | null;
    endTime?: string | null;
    arrivalTime?: string | null;
  };
  /**
   * Odhadovaná cena cestovného (pouze informativní, nezahrnuje se do ceny)
   */
  travelFeeAmount?: number | null;
  status: {
    company: 'pending' | 'confirmed' | 'cancelled';
    user: 'pending' | 'confirmed' | 'cancelled';
    listing: 'active' | 'unavailable';
    variant: 'active' | 'unavailable';
  };
  pricing: {
    mode: 'fixed' | 'open';
    quotedPrice?: number | null;
    agreedPrice?: number | null;
  };
  activity: {
    lastCompanyMessageSentAt?: string | null;
    lastUserMessageSentAt?: string | null;
    lastUserSeenAt?: string | null;
    lastCompanySeenAt?: string | null;
  };
  snapshots: {
    listing?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    variant?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events".
 */
export interface CalendarEvent {
  id: string;
  listing: string | Listing;
  spaces?: (string | Space)[] | null;
  inquiry?: (string | null) | Inquiry;
  startsAt: string;
  endsAt: string;
  allDay?: boolean | null;
  source: 'manual' | 'inquiry';
  status: 'confirmed' | 'tentative' | 'cancelled';
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourite-listings".
 */
export interface FavouriteListing {
  id: string;
  user: string | User;
  listing: string | Listing;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: string;
  token: string;
  email: string;
  company: string | Company;
  role: 'admin' | 'manager' | 'editor';
  status: 'pending' | 'accepted' | 'cancelled';
  invitedBy: string | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items".
 */
export interface RoadmapItem {
  id: string;
  name: string;
  description?: string | null;
  votes?: number | null;
  status?: ('planned' | 'in-progress' | 'completed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications".
 */
export interface UserNotification {
  id: string;
  user: string | User;
  type: 'general' | 'inquiry' | 'event' | 'system';
  heading: string;
  text: string;
  link?: string | null;
  seen?: boolean | null;
  seenAt?: string | null;
  clicked?: boolean | null;
  clickedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-subscriptions".
 */
export interface ListingSubscription {
  id: string;
  listing: string | Listing;
  company: string | Company;
  tariff: 'basic';
  /**
   * Očekávaná částka v Kč
   */
  amount: number;
  status: 'pending' | 'paid' | 'cancelling' | 'expired';
  /**
   * Datum expirace subscription
   */
  validUntil?: string | null;
  paidAt?: string | null;
  /**
   * Stripe Customer ID (cus_...)
   */
  stripeCustomerId?: string | null;
  /**
   * Stripe Subscription ID (sub_...) pro opakované platby
   */
  stripeSubscriptionId?: string | null;
  /**
   * Stripe Payment Intent ID (pi_...) pro jednorázové platby
   */
  stripePaymentIntentId?: string | null;
  /**
   * Stripe Price ID (price_...) — který produkt/tariff byl zakoupen
   */
  stripePriceId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-accounts".
 */
export interface OauthAccount {
  id: string;
  user: string | User;
  provider: 'google';
  providerAccountId: string;
  email?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendEmail' | 'sendPushNotification';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendEmail' | 'sendPushNotification') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'districts';
        value: string | District;
      } | null)
    | ({
        relationTo: 'necessities';
        value: string | Necessity;
      } | null)
    | ({
        relationTo: 'entertainment-types';
        value: string | EntertainmentType;
      } | null)
    | ({
        relationTo: 'dietary-options';
        value: string | DietaryOption;
      } | null)
    | ({
        relationTo: 'food-service-types';
        value: string | FoodServiceType;
      } | null)
    | ({
        relationTo: 'regions';
        value: string | Region;
      } | null)
    | ({
        relationTo: 'dish-types';
        value: string | DishType;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'admins';
        value: string | Admin;
      } | null)
    | ({
        relationTo: 'user-media';
        value: string | UserMedia;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'event-types';
        value: string | EventType;
      } | null)
    | ({
        relationTo: 'listings';
        value: string | Listing;
      } | null)
    | ({
        relationTo: 'spaces';
        value: string | Space;
      } | null)
    | ({
        relationTo: 'personnel';
        value: string | Personnel;
      } | null)
    | ({
        relationTo: 'companies';
        value: string | Company;
      } | null)
    | ({
        relationTo: 'countries';
        value: string | Country;
      } | null)
    | ({
        relationTo: 'cities';
        value: string | City;
      } | null)
    | ({
        relationTo: 'place-types';
        value: string | PlaceType;
      } | null)
    | ({
        relationTo: 'venue-rules';
        value: string | VenueRule;
      } | null)
    | ({
        relationTo: 'gastro-rules';
        value: string | GastroRule;
      } | null)
    | ({
        relationTo: 'entertainment-rules';
        value: string | EntertainmentRule;
      } | null)
    | ({
        relationTo: 'food-preparation-styles';
        value: string | FoodPreparationStyle;
      } | null)
    | ({
        relationTo: 'space-rules';
        value: string | SpaceRule;
      } | null)
    | ({
        relationTo: 'music-genres';
        value: string | MusicGenre;
      } | null)
    | ({
        relationTo: 'technologies';
        value: string | Technology;
      } | null)
    | ({
        relationTo: 'amenities';
        value: string | Amenity;
      } | null)
    | ({
        relationTo: 'room-amenities';
        value: string | RoomAmenity;
      } | null)
    | ({
        relationTo: 'cuisines';
        value: string | Cuisine;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: string | ChatMessage;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: string | Inquiry;
      } | null)
    | ({
        relationTo: 'calendar-events';
        value: string | CalendarEvent;
      } | null)
    | ({
        relationTo: 'favourite-listings';
        value: string | FavouriteListing;
      } | null)
    | ({
        relationTo: 'invitations';
        value: string | Invitation;
      } | null)
    | ({
        relationTo: 'space-types';
        value: string | SpaceType;
      } | null)
    | ({
        relationTo: 'listing-entertainment-details';
        value: string | ListingEntertainmentDetail;
      } | null)
    | ({
        relationTo: 'listing-gastro-details';
        value: string | ListingGastroDetail;
      } | null)
    | ({
        relationTo: 'listing-venue-details';
        value: string | ListingVenueDetail;
      } | null)
    | ({
        relationTo: 'roadmap-items';
        value: string | RoadmapItem;
      } | null)
    | ({
        relationTo: 'user-notifications';
        value: string | UserNotification;
      } | null)
    | ({
        relationTo: 'listing-subscriptions';
        value: string | ListingSubscription;
      } | null)
    | ({
        relationTo: 'oauth-accounts';
        value: string | OauthAccount;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user:
    | {
        relationTo: 'users';
        value: string | User;
      }
    | {
        relationTo: 'admins';
        value: string | Admin;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "districts_select".
 */
export interface DistrictsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  region?: T;
  country?: T;
  bboxMinLon?: T;
  bboxMinLat?: T;
  bboxMaxLon?: T;
  bboxMaxLat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "necessities_select".
 */
export interface NecessitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-types_select".
 */
export interface EntertainmentTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dietary-options_select".
 */
export interface DietaryOptionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-service-types_select".
 */
export interface FoodServiceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  country?: T;
  bboxMinLon?: T;
  bboxMinLat?: T;
  bboxMaxLon?: T;
  bboxMaxLat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dish-types_select".
 */
export interface DishTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  phone?:
    | T
    | {
        countryCode?: T;
        number?: T;
      };
  roles?: T;
  gdprConsent?: T;
  termsOfUseConsent?: T;
  lastRoadmapVoteAt?: T;
  marketingConsent?: T;
  loginToken?: T;
  loginTokenExpiration?: T;
  emailVerificationToken?: T;
  emailVerificationTokenExpiration?: T;
  pendingEmail?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-media_select".
 */
export interface UserMediaSelect<T extends boolean = true> {
  filename?: T;
  alt?: T;
  width?: T;
  height?: T;
  size?: T;
  mimeType?: T;
  bucket?: T;
  user?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  listing?: T;
  status?: T;
  capacity?:
    | T
    | {
        min?: T;
        max?: T;
      };
  name?: T;
  shortDescription?: T;
  description?: T;
  price?:
    | T
    | {
        base?: T;
        pricingUnit?: T;
        seasonalPrices?:
          | T
          | {
              amount?: T;
              adjustmentType?: T;
              valueType?: T;
              title?: T;
              from?: T;
              to?: T;
              id?: T;
            };
      };
  includes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  excludes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  duration?:
    | T
    | {
        hasExactDuration?: T;
        exactDurationMinutes?: T;
        maxDurationMinutes?: T;
      };
  images?:
    | T
    | {
        coverImage?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        gallery?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
              id?: T;
            };
      };
  details?:
    | T
    | {
        venue?:
          | T
          | {
              includedSpaces?: T;
              accommodation?:
                | T
                | {
                    included?: T;
                    capacity?: T;
                  };
              breakfast?:
                | T
                | {
                    included?: T;
                    price?: T;
                    loweredPrice?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gastro?:
          | T
          | {
              kidsMenu?: T;
              alcoholIncluded?: T;
              minimumOrderAmount?: T;
              id?: T;
              blockName?: T;
            };
        entertainment?:
          | T
          | {
              audience?: T;
              performance?:
                | T
                | {
                    entertainmentIsPerformance?: T;
                    numberOfSets?: T;
                    pauseBetweenSetsInMinutes?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-types_select".
 */
export interface EventTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listings_select".
 */
export interface ListingsSelect<T extends boolean = true> {
  tariff?: T;
  type?: T;
  subType?: T;
  filters?:
    | T
    | {
        eventTypes?: T;
        allEventTypes?: T;
        necessities?: T;
        placeTypes?: T;
        venueRules?: T;
        musicGenres?: T;
        entertainmentRules?: T;
        gastroRules?: T;
        dietaryOptions?: T;
        dishTypes?: T;
      };
  options?:
    | T
    | {
        cuisines?: T;
        foodPreparationStyles?: T;
        services?: T;
        technologies?: T;
        personnel?: T;
        amenities?: T;
        activities?: T;
      };
  detail?: T;
  location?:
    | T
    | {
        point?: T;
        address?: T;
        city?: T;
        country?: T;
      };
  servicableArea?:
    | T
    | {
        wholeCountry?: T;
        maxTravelDistanceKm?: T;
      };
  name?: T;
  slug?: T;
  status?: T;
  subscriptionStatus?: T;
  company?: T;
  description?: T;
  shortDescription?: T;
  indoor?: T;
  outdoor?: T;
  guests?:
    | T
    | {
        min?: T;
        max?: T;
        ztp?: T;
        pets?: T;
      };
  images?:
    | T
    | {
        coverImage?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        logo?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        gallery?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
              id?: T;
            };
      };
  minimumPricePerEvent?: T;
  pricingUnit?: T;
  minimumVariantPrice?: T;
  variantPricingUnit?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "spaces_select".
 */
export interface SpacesSelect<T extends boolean = true> {
  status?: T;
  price?:
    | T
    | {
        base?: T;
        pricingUnit?: T;
        seasonalPrices?:
          | T
          | {
              amount?: T;
              adjustmentType?: T;
              valueType?: T;
              title?: T;
              from?: T;
              to?: T;
              id?: T;
            };
      };
  name?: T;
  type?: T;
  parent?: T;
  listing?: T;
  description?: T;
  capacity?: T;
  area?: T;
  images?:
    | T
    | {
        filename?: T;
        alt?: T;
        width?: T;
        height?: T;
        size?: T;
        mimeType?: T;
        bucket?: T;
        id?: T;
      };
  hasAccommodation?: T;
  accommodationCapacity?: T;
  accommodationRooms?:
    | T
    | {
        name?: T;
        capacity?: T;
        countOfRoomsOfThisType?: T;
        amenities?: T;
        id?: T;
      };
  spaceRules?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personnel_select".
 */
export interface PersonnelSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "companies_select".
 */
export interface CompaniesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  ico?: T;
  description?: T;
  logo?:
    | T
    | {
        filename?: T;
        alt?: T;
        width?: T;
        height?: T;
        size?: T;
        mimeType?: T;
        bucket?: T;
      };
  email?: T;
  phone?:
    | T
    | {
        countryCode?: T;
        number?: T;
      };
  website?: T;
  owner?: T;
  billingAddress?:
    | T
    | {
        street?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  vatId?: T;
  members?:
    | T
    | {
        user?: T;
        invitationEmail?: T;
        role?: T;
        id?: T;
      };
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "countries_select".
 */
export interface CountriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  latitude?: T;
  longitude?: T;
  bboxMinLon?: T;
  bboxMinLat?: T;
  bboxMaxLon?: T;
  bboxMaxLat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  code?: T;
  district?: T;
  region?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  bboxMinLon?: T;
  bboxMinLat?: T;
  bboxMaxLon?: T;
  bboxMaxLat?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "place-types_select".
 */
export interface PlaceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venue-rules_select".
 */
export interface VenueRulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gastro-rules_select".
 */
export interface GastroRulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "entertainment-rules_select".
 */
export interface EntertainmentRulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "food-preparation-styles_select".
 */
export interface FoodPreparationStylesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-rules_select".
 */
export interface SpaceRulesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "music-genres_select".
 */
export interface MusicGenresSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technologies_select".
 */
export interface TechnologiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "amenities_select".
 */
export interface AmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "room-amenities_select".
 */
export interface RoomAmenitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cuisines_select".
 */
export interface CuisinesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  eventType?: T;
  budget?: T;
  notes?:
    | T
    | {
        title?: T;
        createdAt?: T;
        description?: T;
        status?: T;
        id?: T;
      };
  checklist?:
    | T
    | {
        label?: T;
        description?: T;
        dueDate?: T;
        completed?: T;
        priority?: T;
        status?: T;
        id?: T;
      };
  icon?: T;
  date?:
    | T
    | {
        start?: T;
        end?: T;
      };
  sharing?:
    | T
    | {
        confirmedInquiries?: T;
        place?: T;
      };
  location?:
    | T
    | {
        district?: T;
        city?: T;
        address?: T;
        spaceType?: T;
        description?: T;
      };
  guests?:
    | T
    | {
        adults?: T;
        children?: T;
        ztp?: T;
        pets?: T;
      };
  contactPerson?:
    | T
    | {
        name?: T;
        email?: T;
        phone?:
          | T
          | {
              countryCode?: T;
              number?: T;
            };
      };
  owner?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  inquiry?: T;
  sender?: T;
  senderType?: T;
  content?:
    | T
    | {
        text?:
          | T
          | {
              text?: T;
              id?: T;
              blockName?: T;
            };
        question?:
          | T
          | {
              text?: T;
              answer?: T;
              answeredAt?: T;
              id?: T;
              blockName?: T;
            };
      };
  sentAt?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  user?: T;
  listing?: T;
  variant?: T;
  event?: T;
  listingType?: T;
  customRequest?:
    | T
    | {
        note?: T;
        addons?:
          | T
          | {
              name?: T;
              optionId?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        spaces?:
          | T
          | {
              spaceId?: T;
              name?: T;
              price?: T;
              pricingUnit?: T;
              id?: T;
            };
        customRequirements?:
          | T
          | {
              text?: T;
              id?: T;
            };
        accommodation?:
          | T
          | {
              guests?: T;
            };
        breakfast?:
          | T
          | {
              guests?: T;
            };
        parking?:
          | T
          | {
              spots?: T;
            };
      };
  serviceTime?:
    | T
    | {
        startTime?: T;
        endTime?: T;
        arrivalTime?: T;
      };
  travelFeeAmount?: T;
  status?:
    | T
    | {
        company?: T;
        user?: T;
        listing?: T;
        variant?: T;
      };
  pricing?:
    | T
    | {
        mode?: T;
        quotedPrice?: T;
        agreedPrice?: T;
      };
  activity?:
    | T
    | {
        lastCompanyMessageSentAt?: T;
        lastUserMessageSentAt?: T;
        lastUserSeenAt?: T;
        lastCompanySeenAt?: T;
      };
  snapshots?:
    | T
    | {
        listing?: T;
        variant?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calendar-events_select".
 */
export interface CalendarEventsSelect<T extends boolean = true> {
  listing?: T;
  spaces?: T;
  inquiry?: T;
  startsAt?: T;
  endsAt?: T;
  allDay?: T;
  source?: T;
  status?: T;
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favourite-listings_select".
 */
export interface FavouriteListingsSelect<T extends boolean = true> {
  user?: T;
  listing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  token?: T;
  email?: T;
  company?: T;
  role?: T;
  status?: T;
  invitedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "space-types_select".
 */
export interface SpaceTypesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-entertainment-details_select".
 */
export interface ListingEntertainmentDetailsSelect<T extends boolean = true> {
  customSections?:
    | T
    | {
        gallery1?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery2?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery4?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery5?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  sectionOrder?:
    | T
    | {
        key?: T;
        id?: T;
      };
  price?:
    | T
    | {
        base?: T;
        pricingUnit?: T;
        seasonalPrices?:
          | T
          | {
              amount?: T;
              adjustmentType?: T;
              valueType?: T;
              title?: T;
              from?: T;
              to?: T;
              id?: T;
            };
        travelFeeEnabled?: T;
        travelFeePerKm?: T;
        travelFeeType?: T;
        travelFeeStartsAtKm?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        group?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        eventName?: T;
        description?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        id?: T;
      };
  type?: T;
  audience?: T;
  filters?:
    | T
    | {
        allEventTypes?: T;
        eventTypes?: T;
        necessities?: T;
        musicGenres?: T;
        entertainmentRules?: T;
      };
  options?:
    | T
    | {
        technologies?:
          | T
          | {
              technology?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        services?:
          | T
          | {
              service?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
      };
  setupAndTearDown?:
    | T
    | {
        setupTime?: T;
        tearDownTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-gastro-details_select".
 */
export interface ListingGastroDetailsSelect<T extends boolean = true> {
  customSections?:
    | T
    | {
        gallery1?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery2?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery4?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery5?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  sectionOrder?:
    | T
    | {
        key?: T;
        id?: T;
      };
  price?:
    | T
    | {
        base?: T;
        pricingUnit?: T;
        seasonalPrices?:
          | T
          | {
              amount?: T;
              adjustmentType?: T;
              valueType?: T;
              title?: T;
              from?: T;
              to?: T;
              id?: T;
            };
        travelFeeEnabled?: T;
        travelFeePerKm?: T;
        travelFeeType?: T;
        travelFeeStartsAtKm?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        group?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        eventName?: T;
        description?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        id?: T;
      };
  type?: T;
  alcohol?:
    | T
    | {
        servesAlcohol?: T;
        pricingUnit?: T;
      };
  kidsMenu?: T;
  filters?:
    | T
    | {
        allEventTypes?: T;
        eventTypes?: T;
        dishTypes?: T;
        necessities?: T;
        dietaryOptions?: T;
        gastroRules?: T;
      };
  options?:
    | T
    | {
        cuisines?:
          | T
          | {
              cuisine?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        foodPreparationStyles?:
          | T
          | {
              foodPreparationStyle?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        services?:
          | T
          | {
              service?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        personnel?:
          | T
          | {
              personnel?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
      };
  setupAndTearDown?:
    | T
    | {
        setupTime?: T;
        tearDownTime?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-venue-details_select".
 */
export interface ListingVenueDetailsSelect<T extends boolean = true> {
  customSections?:
    | T
    | {
        gallery1?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery2?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery4?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        gallery5?:
          | T
          | {
              title?: T;
              text?: T;
              images?:
                | T
                | {
                    filename?: T;
                    alt?: T;
                    width?: T;
                    height?: T;
                    size?: T;
                    mimeType?: T;
                    bucket?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  sectionOrder?:
    | T
    | {
        key?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        active?: T;
        question?: T;
        answer?: T;
        group?: T;
        id?: T;
      };
  references?:
    | T
    | {
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        eventName?: T;
        description?: T;
        clientName?: T;
        eventType?: T;
        id?: T;
      };
  employees?:
    | T
    | {
        name?: T;
        role?: T;
        description?: T;
        image?:
          | T
          | {
              filename?: T;
              alt?: T;
              width?: T;
              height?: T;
              size?: T;
              mimeType?: T;
              bucket?: T;
            };
        id?: T;
      };
  type?: T;
  spacesType?: T;
  area?: T;
  canBeBookedAsWhole?: T;
  accomodation?:
    | T
    | {
        hasAccommodation?: T;
        accommodationCapacity?: T;
      };
  propertyAccess?:
    | T
    | {
        vehicleTypes?: T;
        loadingRamp?: T;
        loadingElevator?: T;
        serviceAccess?: T;
        serviceArea?: T;
      };
  storage?:
    | T
    | {
        name?: T;
        area?: T;
        space?: T;
        accessedFrom?: T;
        id?: T;
      };
  parking?:
    | T
    | {
        hasParking?: T;
        parkingCapacity?: T;
        parkingIsIncludedInPrice?: T;
        parkingPrice?: T;
        parkingPriceUnit?: T;
      };
  filters?:
    | T
    | {
        allEventTypes?: T;
        eventTypes?: T;
        placeTypes?: T;
        venueRules?: T;
        necessities?: T;
      };
  options?:
    | T
    | {
        activities?:
          | T
          | {
              activity?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        technologies?:
          | T
          | {
              technology?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        personnel?:
          | T
          | {
              personnel?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        amenities?:
          | T
          | {
              amenity?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        services?:
          | T
          | {
              service?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
      };
  catering?:
    | T
    | {
        hasCatering?: T;
        cateringIsIncludedInPrice?: T;
        price?: T;
        pricingUnit?: T;
        cuisines?:
          | T
          | {
              cuisine?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
        foodPreparationStyles?:
          | T
          | {
              foodPreparationStyle?: T;
              pricingUnit?: T;
              unitPrice?: T;
              quantity?: T;
              id?: T;
            };
      };
  breakfast?:
    | T
    | {
        breakfastIncluded?: T;
        allowAccommodationWithoutBreakfast?: T;
        allowMoreBreakfastsThanAccommodation?: T;
        breakfastIsIncludedInPrice?: T;
        price?: T;
        priceUnit?: T;
        timeFrom?: T;
        timeTo?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roadmap-items_select".
 */
export interface RoadmapItemsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  votes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-notifications_select".
 */
export interface UserNotificationsSelect<T extends boolean = true> {
  user?: T;
  type?: T;
  heading?: T;
  text?: T;
  link?: T;
  seen?: T;
  seenAt?: T;
  clicked?: T;
  clickedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "listing-subscriptions_select".
 */
export interface ListingSubscriptionsSelect<T extends boolean = true> {
  listing?: T;
  company?: T;
  tariff?: T;
  amount?: T;
  status?: T;
  validUntil?: T;
  paidAt?: T;
  stripeCustomerId?: T;
  stripeSubscriptionId?: T;
  stripePaymentIntentId?: T;
  stripePriceId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oauth-accounts_select".
 */
export interface OauthAccountsSelect<T extends boolean = true> {
  user?: T;
  provider?: T;
  providerAccountId?: T;
  email?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendEmail".
 */
export interface TaskSendEmail {
  input: {
    email: string;
    body: string;
    subject: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendPushNotification".
 */
export interface TaskSendPushNotification {
  input: {
    title: string;
    message: string;
    accountId: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}